export const SET_SEARCHED_DATA = 'SET_SEARCHED_DATA'
export const SET_GIT_USERS_DATA = "SET_GIT_USERS_DATA"
export const GET_USER_DATA = 'GET_USER_DATA'
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA'